# GitHub Copilot Agent Configuration
# This configuration sets up a development environment for the Playwright MCP server
# with all necessary dependencies pre-installed to speed up development

name: playwright-mcp-development-environment
description: Development environment for Playwright MCP server with Node.js, Playwright, and all dependencies pre-configured

# Base image configuration
image: ubuntu-latest

# Environment setup steps (based on CI workflow)
setup:
  # System dependencies
  - name: Install system packages
    run: |
      apt-get update
      apt-get install -y git curl wget build-essential ca-certificates
  
  # Node.js setup (matching CI workflow version)
  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: '18.19'
      cache: 'npm'
  
  # Install project dependencies
  - name: Install npm dependencies
    run: npm ci
    
  # Install Playwright browsers and system dependencies
  - name: Install Playwright with dependencies
    run: npx playwright install --with-deps
    
  # Build the project
  - name: Build project
    run: npm run build
    
  # Verify installation
  - name: Verify setup
    run: |
      node --version
      npm --version
      npx playwright --version

# Runtime configuration
runtime:
  node_version: '18.19'
  npm_cache: true
  
# Environment variables
env:
  NODE_ENV: development
  DEBUG: "playwright*"
  PLAYWRIGHT_BROWSERS_PATH: "/ms-playwright"

# Workspace configuration  
workspace:
  directory: "/workspace"
  
# Pre-installed tools and their versions
tools:
  node: "18.19"
  npm: "latest" 
  playwright: "1.55.0-alpha-1752701791000"
  typescript: "^5.8.2"

# Development scripts shortcuts
scripts:
  build: "npm run build"
  test: "npm test"
  lint: "npm run lint"
  watch: "npm run watch"
  clean: "npm run clean"

# Playwright specific configuration
playwright:
  browsers:
    - chromium
    - firefox
    - webkit
  install_system_deps: true
  browsers_path: "/ms-playwright"

# Additional metadata
metadata:
  maintainer: "Microsoft Corporation"
  documentation: "https://github.com/microsoft/playwright-mcp"
  version: "1.0.0"